### ISSUE TITLE
Change Area_m2 fields in suitability layers to a double from a long

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/PEW-EFH#21]
- [x] do this to allow values greater than 1 billion
- [x] Have Ryan update clickAttributes.js to remove decimal places (ticket forthcoming)

**Comment by ghost** [comment]
Hey Ryan,

I have finished updating all of the area_m2 fields from long integers to doubles, allowing for the full number to be displayed.  I also updated all of the area calculations with new figures using an equal area projection.  The planning unit grid shapefile has been updated with all of the changes and is here: \neoterra\GIS\projects\PewEFH2015\Data\Processed\PEW_final_datasets\Planning_unit_grid\PEW_5nm_PUG.shp.  The table describing the datasets included in the PUG is updated too and is here: \neoterra\GIS\projects\PewEFH2015\Util\Tables\Data_package_status.xlsx.  The worksheet tab is: "pug_fields".  Remeber to update the clickAttributes.js to remove decimal places.  Let me know if you have any questions.

**Comment by rhodges** [comment]
Leaving class 4 Antipatharia out of reports - no class 4 habitat exists.
what about:
- [x] cs_obs
- [x] cs_spm
- [x] cs3500_obs
- [x] cs3500_spm

**Comment by ghost** [comment]
Hey Ryan,

Sounds good about leaving hsanti4_m2 field out.  There is also no values for hssclr4_m2, so that can be left out too.  I had them in there just so it was clear that there were no values, but it seems unnecessary to leave them.

As for the cs_obs, cs_spm, cs3500_obs, and cs3500_spm, they all have values and should be included.  As for what they are:

·         Cs_obs is the number of deep sea coral and sponge observations within the EEZ summarized to the PUG

·         Cs_spm is the actual number of specimens that we counted during the observations within the EEZ summarized to the PUG

·         Cs3500_obs is the number of deep sea coral and sponge observations deeper than 3500 meters summarized to the PUG

·         Cs3500_spm is the actual number of specimens that we counted during the observations deeper than 3500 meters summarized to the PUG

Let me know if this is what you were getting at with your question or if this created more questions.

Thanks,
Nick

Nick Lyman | GIS Analyst | Ecotrust
721 NW 9th Avenue, Suite 200 • Portland, OR 97209
T (503) 467.0759 | www.ecotrust.orghttp://www.ecotrust.org/
