### ISSUE TITLE
Add Tribal UA Layer

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/PEW-EFH#32]
Jon has the information describing these areas if you don't already.

Nick:
- [x] Gather .shp files and list location in the comments
- [x] Generate .xml files and list location in the comments
- [x] Generate legend .png files and list location in the comments

Ryan:
- [x] Upload .shp and .xml files to appropriate place on tile server
- [x] Configure .xml file
- [x] Configure tilestache
- [x] Add layers to tool and test
- [x] check in legend
- [x] Add legend to tool

**Comment by ghost** [comment]
Hey Ryan, there are 4 new datasets for you to load pertaining to the tribal U+A.  There is overlap between the 4 layers, so that is why there are 4 insead of one...

Spatial data: \neoterra\GIS\projects\PewEFH2015\Data\Processed\PEW_final_datasets\Tribal_lands
  \Hoh_UA.shp
  \Makah_UA.shp
  \Quileute_UA.shp
  \Quinault_UA.shp

xmls: \neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Mapnik_xml
  \PEW_tribal_UA_Hoh.xml
  \PEW_tribal_UA_Makah.xml
  \PEW_tribal_UA_Quileute.xml
  \PEW_tribal_UA_Quinault.xml

legends: \neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Legend_pngs
  \PEW_tribal_UA_Hoh.png
  \PEW_tribal_UA_Makah.png
  \PEW_tribal_UA_Quileute.png
  \PEW_tribal_UA_Quinault.png
